import os

AZURE_SEARCH_EMAILS_INDEX_URL = os.getenv('AZURE_SEARCH_EMAILS_INDEX_URL')
AZURE_SEARCH_API_KEY = os.getenv('AZURE_SEARCH_API_KEY')
MONGO_DB_NAME = os.getenv('MONGO_DB_NAME')
MONGO_CXN_STR = os.getenv('MONGO_CXN_STR')
BLOB_STORAGE_CONNECTION_STRING = os.getenv('BLOB_STORAGE_CONNECTION_STRING')
BLOB_STORAGE_CONTAINER = os.getenv("BLOB_STORAGE_CONTAINER")

for setting in [
    AZURE_SEARCH_EMAILS_INDEX_URL,
    AZURE_SEARCH_API_KEY,
    MONGO_DB_NAME,
    MONGO_CXN_STR,
    BLOB_STORAGE_CONNECTION_STRING,
    BLOB_STORAGE_CONTAINER
]:
    if not setting:
        raise EnvironmentError("Missing environment variable!")